export const ADD_NEW_GROUP = 'ADD_NEW_GROUP'
export const ADD_NEW_TASK = 'ADD_NEW_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_GROUP = 'DELETE_GROUP'
export const CHANGE_TITLE = 'CHANGE_TITLE'
